(defglobal ?*R-DEVICE_PATH* = "C:\\Program Files\\R-DEVICE\\")
(load* (str-cat ?*R-DEVICE_PATH* "rdf.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "classes.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "auxiliary-functions.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "class-functions.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "aggregates.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "types.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "oo-querying.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "second-order.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "stratification.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "translation.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "translation-rules.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "main.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "rdf-auxiliary.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "load-rdf.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "import.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "export.clp"))
(load* (str-cat ?*R-DEVICE_PATH* "triple-transformation.clp"))
(reset)
